piVersion: v1alpha1
kind: RepositoryContent
services:
- apiVersion: v1alpha1
  kind: ServiceTemplate
  metadata:
    creationTimestamp: "0001-01-01T00:00:00Z"
    name: nginx-with-bootstrap
    platforms:
    - linux
  spec:
    description: NGINX with Bootstrap
    icon: https://docker-application-template.s3.amazonaws.com/assets/nginx.png
    parameters:
    - defaultValue: "1.15-alpine"
      description: Version
      name: nginxVersion
      type: enum
      values:
      - description: "1.17-alpine"
        value: "1.17-alpine"
      - description: "1.16-alpine"
        value: "1.16-alpine"
      - description: "1.15-alpine"
        value: "1.15-alpine"
    - defaultValue: "8080"
      description: External port
      name: externalPort
      type: hostPort
    source:
      image: dtr.build.us.se.dckr.org/service-template/nginx-with-bootstrap:latest
    title: NGINX with Bootstrap

