piVersion: v1alpha1
kind: RepositoryContent
services:
- apiVersion: v1alpha1
  kind: ServiceTemplate
  metadata:
    creationTimestamp: "0001-01-01T00:00:00Z"
    name: nginx-with-bootstrap
    platforms:
    - linux
  spec:
    description: NGINX with Bootstrap
    icon: https://docker-application-template.s3.amazonaws.com/assets/nginx.png
    parameters:
    - defaultValue: "1.15-alpine"
      description: Version
      name: nginxVersion
      type: enum
      values:
      - description: "1.17-alpine"
        value: "1.17-alpine"
      - description: "1.16-alpine"
        value: "1.16-alpine"
      - description: "1.15-alpine"
        value: "1.15-alpine"
    - defaultValue: "8080"
      description: External port
      name: externalPort
      type: hostPort
    source:
      image: dtr.build.us.se.dckr.org/service-template/nginx-with-bootstrap:latest
    title: NGINX with Bootstrap
- apiVersion: v1alpha1
  kind: ServiceTemplate
  metadata:
    name: aspnet-mvc
    platforms:
      - windows
  spec:
    description: ASP.NET web application using the MVC Framework
    icon: https://applicationdesigner.s3.amazonaws.com/assets/aspnetcore.png
    parameters:
    - name: externalPort
      description: External Port
      type: string
      defaultValue: "8000"
    source:
      image: dtr.build.us.se.dckr.org/service-template/aspnet-mvc:latest
    title: ASP.NET Framework - MVC
- apiVersion: v1alpha1
  kind: ServiceTemplate
  metadata:
    name: aspnet-webforms
    platforms:
      - windows
  spec:
    description: ASP.NET web application
    icon: https://applicationdesigner.s3.amazonaws.com/assets/aspnetcore.png
    parameters:
    - name: externalPort
      description: External Port
      type: string
      defaultValue: "8000"
    source:
      image: dtr.build.us.se.dckr.org/service-template/aspnet-webforms:latest
    title: ASP.NET Framework - Web Forms
- apiVersion: v1alpha1
  kind: ServiceTemplate
  metadata:
    name: wcf
    platforms:
      - windows
  spec:
    description: Application implementing Windows Communication Framework (WCF)
    icon: https://applicationdesigner.s3.amazonaws.com/assets/aspnetcore.png
    parameters:
    - name: externalPort
      description: External Port
      type: string
      defaultValue: "8000"
    source:
      image: dtr.build.us.se.dckr.org/service-template/wcf:latest
    title: Windows Communication Framework (WCF)
- apiVersion: v1alpha1
  kind: ServiceTemplate
  metadata:
    creationTimestamp: "0001-01-01T00:00:00Z"
    name: signup-database
    platforms:
    - linux
  spec:
    description: MySQL Database
    icon: https://docker-application-template.s3.amazonaws.com/assets/mysql.png
    parameters:
    - defaultValue: "8.0.15"
      description: MySQL Version
      name: mysqlVersion
      type: enum
      values:
      - description: "5.7.24"
        value: "5.7.24"
      - description: "5.6.42"
        value: "5.6.42"
    - defaultValue: "signup"
      description: Database name
      name: mysqlDatabaseName
      type: string
    - defaultValue: "gordon"
      description: Username
      name: mysqlUserName
      type: string
    - defaultValue: "password"
      description: Password
      name: mysqlPassword
      type: string
    source:
      image: dtr.build.us.se.dckr.org/service-template/signup-database:latest
    title: MySQL Database for Signup App
