version: '3.3'

services:

  database:
    image: dockersamples/hybrid-app-db
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
    - mode: ingress
      published: 3306
      target: 3306
    networks:
      back-tier: null
    deploy:
      placement:
        constraints:
        - node.platform.os == linux

  java-app:
    image: dockersamples/hybrid-app-web:v1
    ports:
    - mode: ingress
      published: 8000
      target: 8000
    - mode: ingress
      published: 8080
      target: 8080
    networks:
      back-tier: null
      front-tier: null
    deploy:
      placement:
        constraints:
        - node.platform.os == linux

networks:
  back-tier: {}
  front-tier: {}