version: "3.3"
services:
 database:
   image: dockersamples/database
   # set default mysql root password, change as needed
   environment:
     MYSQL_ROOT_PASSWORD: mysql_password
   # Expose port 3306 to host.
   ports:
     - "3306:3306"
   networks:
     - back-tier
 webserver:
   image: dockersamples/hybrid-app-web
   ports:
     - "8080:8080"
   networks:
     - front-tier
     - back-tier
networks:
 back-tier:
 front-tier: